### ISSUE TITLE
String interpolation inside object declaration fails with an error on Haxe 4.3

### ISSUE THREAD

**Issue by theJenix** [haxetink/tink_hxx#62]
Using string interpolation inside objects inside hxx compiles fine in Haxe 4.2.5 but results in a `Reification $ is not allowed outside of `macro` expression` error in Haxe 4.3 (specifically, Haxe 4.3.1 but I believe this is true for Haxe 4.3.0 as well).  I think I know what's going on and have a PR I can submit but I wanted to start with an issue just in case I might be missing something.

# Example problem
```
<div style={{ height: ${height} }} />
```

# Investigation
It looks like the issue results from changes made in Haxe 4.3 where they tightened up where the macro reification operator can be used.  When tink_hxx parses that, eventually it will pass `"{ height: ${height} }"` to `Context.parseInlineString(source, pos)`.  This will parse that statement into an EObjectDecl with one field, and the expression for that field will be EMeta where $ is the MetadataEntry and EConst(CIdent(height)) is the expression.  On Haxe 4.2.5, it appears that this EMeta passes through tink_hxx and is emitted as the string representation ${height}, which is then interpolated.  On Haxe 4.3, this appears to happen exactly as stated except the $ is interpreted as a reification operator (hence the error.)

# Potential Fix
From what I can see, it looks like the fix to this might be to process the return from `Context.parseInlineString`, and if it is an EObjectDecl find any fields with an expression matching the EMeta value described above and replace the field expression with the EMeta inner expression.

I have a PR ready to submit for review, if y'all would like.  I tried to write a test in RunTests for this but I was having some trouble figuring out how to test this, so I would love advice on that.

**Comment by back2dos** [comment]
I'm confused. Why not just write `<div style={{ height: height }} />`?

**Comment by theJenix** [comment]
Sorry for the delay!  That would work, but I have a lot of code that was written prior to the change that broke this in Haxe 4.3 that I do not want to have to go back and fix.  As a general rule, I used Haxe interpolation because VS Code + vshaxe colored/highlighted the interpolated part differently; i.e. it behaved more like other string interpolation than using JSX like syntax.  According to the tink_hxx readme, this is supported and it worked prior to Haxe 4.3, so I think it's reasonable to expect it to continue to work going forward.  I have a PR ready to review; would you be interested in reviewing it?

**Comment by back2dos** [comment]
>  As a general rule, I used Haxe interpolation because VS Code + vshaxe colored/highlighted the interpolated part differently; i.e. it behaved more like other string interpolation than using JSX like syntax.

You can do `<div style=${{ height: height }} />` if you wish to use Haxe's string interpolation syntax.

> According to the tink_hxx readme, this is supported

No. The readme says is that you can embed expressions using JSX style or Haxe string interpolation style. What you have is Haxe macro reification syntax nested in JSX style. It happened to work because `${height}` was simply processed as `height` by the compiler, but that was undefined behavior that is no longer supported in Haxe 4.3. I'm sorry that the compiler changes inconvenience you, but tink_hxx really has nothing to do with that.

**Comment by kLabz** [comment]
Hi!

There's another fix which would be removing `$` (and _not_ other reification like `$p` and such) from `Context.parse` / `Context.parseInlineString` return with a simple expr map: https://try.haxe.org/#8EA0FA99

**Comment by back2dos** [comment]
> So, you aren't interested in looking at a pull request for this? I have a solution to support this and am happy to submit it and take feedback on how to write tests for it. The justification for supporting this syntax (and ultimately, the fix) is that this is just string interpolation which creates the JSX/HXX string which is then passed into your macro. This appears easy to detect and unwrap inside the Haxe macro, and makes for a much better developer experience imho.

I don't agree with your premise. It is not "just string interpolation". HXX allows `{}` primarily to be more compatible with JSX, so that people can more easily migrate or stick with the style they're more used to. In any case, it is supposed to be equivalent to `${}`. And so `'<div style={{ height: ${height} }} />'` is equivalent to `'<div style=${{ height: ${height} }} />'`, which is no longer valid in Haxe 4.3: https://try.haxe.org/#7DB4aE30

Conceptually, I think it's very clear to say that what goes between `{}` or `${}` must be a valid expression. 

It is perfectly valid to write `<div style={{ height: height }} />` or `<div style=${{ height: height }} />` if you want plain Haxe syntax highlighting (although I would suggest considering https://marketplace.visualstudio.com/items?itemName=influrium.haxe-jsx) and I would argue that `<div style=${{ height: height, width: width, transform: transform }} />` is nicer than `<div style={{ height: ${height}, width: ${width}, transform: ${transform} }} />` either way.

Regarding a PR, I would not want this as a default behavior, because for one it adds a syntax rule, which IMHO is pretty arbitrary and has no evident benefit. And mapping *every* expression to support this does not come for free either.

Of course I don't want users to go through the trouble of maintaining their own forks (unless they really want to), but in this case I would suggest hanging onto it until this is solved in 4.3.2, which is hopefully around the corner.

To deal with similar situations, I suppose I would prefer figuring out a way that allows users to plug in such special behaviors.
